/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RelancesRouteImport } from './routes/relances'
import { Route as DevisClientRefRouteImport } from './routes/devis-client.$ref'
import { Route as DossiersIndexRouteImport } from './routes/dossiers.index'
import { Route as DossiersRefRouteImport } from './routes/dossiers.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RelancesRoute = RelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisClientRefRoute = DevisClientRefRouteImport.update({
  id: '/devis-client/$ref',
  path: '/devis-client/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersIndexRoute = DossiersIndexRouteImport.update({
  id: '/dossiers/',
  path: '/dossiers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRefRoute = DossiersRefRouteImport.update({
  id: '/dossiers/$ref',
  path: '/dossiers/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/dashboard': typeof DashboardRoute
  '/relances': typeof RelancesRoute
  '/devis-client/$ref': typeof DevisClientRefRoute
  '/dossiers/$ref': typeof DossiersRefRoute
  '/dossiers/': typeof DossiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/dashboard': typeof DashboardRoute
  '/relances': typeof RelancesRoute
  '/devis-client/$ref': typeof DevisClientRefRoute
  '/dossiers/$ref': typeof DossiersRefRoute
  '/dossiers': typeof DossiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/dashboard': typeof DashboardRoute
  '/relances': typeof RelancesRoute
  '/devis-client/$ref': typeof DevisClientRefRoute
  '/dossiers/$ref': typeof DossiersRefRoute
  '/dossiers/': typeof DossiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuration'
    | '/dashboard'
    | '/relances'
    | '/devis-client/$ref'
    | '/dossiers/$ref'
    | '/dossiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuration'
    | '/dashboard'
    | '/relances'
    | '/devis-client/$ref'
    | '/dossiers/$ref'
    | '/dossiers'
  id:
    | '__root__'
    | '/'
    | '/configuration'
    | '/dashboard'
    | '/relances'
    | '/devis-client/$ref'
    | '/dossiers/$ref'
    | '/dossiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurationRoute: typeof ConfigurationRoute
  DashboardRoute: typeof DashboardRoute
  RelancesRoute: typeof RelancesRoute
  DevisClientRefRoute: typeof DevisClientRefRoute
  DossiersRefRoute: typeof DossiersRefRoute
  DossiersIndexRoute: typeof DossiersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relances': {
      id: '/relances'
      path: '/relances'
      fullPath: '/relances'
      preLoaderRoute: typeof RelancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis-client/$ref': {
      id: '/devis-client/$ref'
      path: '/devis-client/$ref'
      fullPath: '/devis-client/$ref'
      preLoaderRoute: typeof DevisClientRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers/': {
      id: '/dossiers/'
      path: '/dossiers'
      fullPath: '/dossiers/'
      preLoaderRoute: typeof DossiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers/$ref': {
      id: '/dossiers/$ref'
      path: '/dossiers/$ref'
      fullPath: '/dossiers/$ref'
      preLoaderRoute: typeof DossiersRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurationRoute: ConfigurationRoute,
  DashboardRoute: DashboardRoute,
  RelancesRoute: RelancesRoute,
  DevisClientRefRoute: DevisClientRefRoute,
  DossiersRefRoute: DossiersRefRoute,
  DossiersIndexRoute: DossiersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
